default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV.fetch('DATABASE_NAME') %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
